### ISSUE TITLE
Backslash-escaped `<` is still treated as an HTML entity

### ISSUE THREAD

**Issue by rwols** [facelessuser/sublime-markdown-popups#112]
The following markdown breaks ST's minihtml renderer.
````
### field `_foo`  

---
Type: `int`  
This is the thing that does blah
@var std::vector\<MyClass> \_foo  

---
```cpp
// In MyClasses
private: int _foo
```
````

**Comment by facelessuser** [comment]
Yup, probably because it needs this fix: https://github.com/facelessuser/pymdown-extensions/pull/1020/files.

I haven't updated to the latest pymdownx dependency yet. I was going to update both that and the Markdown dependency, but the current Markdown release updated the HTML parser and is a bit flakey currently. I may update us to 3.2.2 for Markdown instead of the latest.

**Comment by facelessuser** [comment]
I'd like to get this in before the next release of mdpopups. This is really the last thing I wanted to get in. I'll revaluate the current Python Markdown. We may go ahead and pull in the latest Markdown, and update pymdown-extensons.

**Comment by facelessuser** [comment]
This was fixed a while ago
