### ISSUE TITLE
HTML5 <details>

### ISSUE THREAD

**Issue by jrappen** [facelessuser/sublime-markdown-popups#25]
Having an issue where:

```markdown
<details>
<summary>Some summary</summary>

...content either md or html if separated by new line from html tags

</details>
```

breaks an mdpopups phantom from the first `<details>` tag on. Everything before that is fine.

**Comment by facelessuser** [comment]
This would be a Python Markdown issue, not Mdpopups.  This would have to be fixed upstream there, and then we could update the Python Markdown dependency in Sublime.  I imagine the issue is that `<details>` is not recognized by Python Markdown as a block [HTML element](https://github.com/waylan/Python-Markdown/blob/master/markdown/util.py#L29) (which it should).   So instead, Python Markdown treats it as inline messing up the processing of it.

**Comment by jrappen** [comment]
* moved to waylan/Python-Markdown#543

**Comment by FichteFoll** [comment]
I also doubt that minihtml is gonna do anything with it, but at least it shouldn't panic.

**Comment by facelessuser** [comment]
I would have to agree here.  I think using details is kind of pointless in minihtml, but it probably shouldn't break proper rendering.
