### ISSUE TITLE
Word wrap for normal text does not work

### ISSUE THREAD

**Issue by deathaxe** [facelessuser/sublime-markdown-popups#27]
A user asked GitGutter to provide word wrapping for normal text in issue https://github.com/jisaacks/GitGutter/issues/379. On my investigations on that topic I found `mdpopups.syntax_highlight()` to completely disable wrapping for all kinds of content.

It seems commit 2e8ff03 which disables word wrap for source code to fix https://github.com/facelessuser/sublime-markdown-popups/issues/14 is causing that issue.

I could work around this issue as follows:

```python
        lang = mdpopups.get_language_from_view(view)
        if lang is 'text':
            content = '<div class="highlight">{0}</div>'.format(
                source_content.replace('\n', '<br>'))
        else:
            content = mdpopups.syntax_highlight(
                view, source_content, language=lang)
```

It seems not very straight forward. So my question is, whether `mdpopups.syntax_highlight()` can enable/disable wrapping by the following rule?

enable word wrap:

```python
mdpopups.syntax_highlight(view, source_content, language='text')
```

disable word wrap:

```python
mdpopups.syntax_highlight(view, source_content, language='python')
```

**Comment by r-stein** [comment]
To really solve the issue I don't think it is sufficient to only disable the wrapping inside plain text, because if the wrapping is disabled for plain text, then other text formats like markdown or LaTeX should also not have the wrapping.

**Comment by facelessuser** [comment]
Let me make sure I understand.  Sometimes you want wrapping, but sometimes you don't?

**Comment by r-stein** [comment]
Yes

**Comment by facelessuser** [comment]
If we want to do this, I won't use language as the basis of wrapping.  Just because I'm not syntax highlighting doesn't mean the structure of what I'm writing isn't important.  Instead, I would just add a wrap option.

I might include this in the next big release coming.  I've been avoiding finishing it, as I've been a little lazy with my plugins recently.  But I've been thinking I should get off my butt and finish it as I feel we are rounding the home stretch for ST3 beta.

**Comment by deathaxe** [comment]
Maybe you could make _mdpopups_ behave a little bit like default wrapping feature of ST. It uses `word_wrap` setting to enable/disable or automatically enable wrapping based on scope. Wrapping is disabled for any text containing 'source' in the scope in "auto" mode. `wrap_width`  is used to determine the maximum line length. It defaults to 0, which means automatically wrapping on viewport width. If set to a value >0 lines are wrapped after the set number of characters. 

Not sure, whether second option is useful or handy for popups, but first one might be.

Fixed line length would maybe require `textwrap.wrap(content, wrap_width)` to be used to wrap content before forwarding to ST.

**Comment by facelessuser** [comment]
> Fixed line length would maybe require textwrap.wrap(content, wrap_width) to be used to wrap content before forwarding to ST.

I have to be honest, I am not looking to provide my own wrapping logic, and by wrapping logic, I mean specifically wrapping the text myself.  If a plugin needs to control wrapping, i.e. physically wrap content to a specific width, I am going to leave that up to the user.  If they want to `textwrap.wrap` their code content, I'll let them do that in their plugin.  I personally don't have need for that, and if I ever do, I would most likely just do it in my plugin before passing it through `mdpopups`.

> It uses word_wrap setting to enable/disable or automatically enable wrapping based on scope. Wrapping is disabled for any text containing 'source' in the scope in "auto" mode. wrap_width is used to determine the maximum line length.

This seems unnecessary to me.  These popups aren't an editor, just a way to display some useful info.  A plugin author knows if they want their content wrapped, so they should just say "I want this wrapped"  or "I don't want this wrapped".  If I made `auto` default, I feel it would confuse some users.  If I don't make it default, then you have to feed in auto on every `mdpopups` call and you gain nothing and should probably just say `wrapping=True` or `wrapping=False`.  I wouldn't make it a global command because I feel that the context of how a plugin is displaying the content is important.

That's just my opinion.  I feel I'd have to be convinced otherwise before heading down the `auto` route.

**Comment by deathaxe** [comment]
Sounds like a plan.

**Comment by facelessuser** [comment]
The parameter will be called `allow_code_wrap`.  Obviously it does not apply to inline as inline already allows wrapping.

**Comment by r-stein** [comment]
Thanks very nice. This will be released in version `1.14.0`?

**Comment by facelessuser** [comment]
2.0.0

**Comment by deathaxe** [comment]
Just tried wrapping with mdpopups master. Works good.

**Comment by facelessuser** [comment]
@deathaxe I'm shooting for a release early June due to the nature of the 2.0 release.

**Comment by deathaxe** [comment]
So GitGutter will be prepared :-)
