### ISSUE TITLE
JSON tests complain about comment indention

### ISSUE THREAD

**Issue by deathaxe** [facelessuser/sublime-markdown-popups#37]
Your JSON tests run indention checks before stripping comments from the JSON file. Even though it is a generally good idea to check comments' indention as well, but it causes some trouble with following comment formats (used by GitSavvy).

#### Example 1

Indention warning is emitted for all lines but 1 even though the comment looks valid.
```
    /*
     *  This setting should only be set to true in the following conditions:
     *
     *  - you have installed the "Codecs33" package from Package Control
     *  - you are running Linux or OS X
     *  - you would like to use non-supported codecs like "gbk" for the
     *    `fallback_encoding` value
     */
```

#### Example 2

Indention warning is emitted for the last comment line which is a continuation of an unsorted list item.
```
    /*
        This setting should only be set to true in the following conditions:

        - you have installed the "Codecs33" package from Package Control
        - you are running Linux or OS X
        - you would like to use non-supported codecs like "gbk" for the
          `fallback_encoding` value
    */
```

#### Example 3

The comments might use a different indention width and therefore warnings are emitted for all list items, and the continuation line. The tailing `*/` is warned about, too, as it is indented to have is `*` in the same column as the leading one.
```
    /*
        This setting should only be set to true in the following conditions:

          - you have installed the "Codecs33" package from Package Control
          - you are running Linux or OS X
          - you would like to use non-supported codecs like "gbk" for the
            `fallback_encoding` value
     */
```

Maybe comments should not be checked for indention or the logic to do so should be extended to support the old C-style formats.

Thoughts? Ideas?

**Comment by facelessuser** [comment]
This is most likely why I currently don't indent check comments, though I most likely intended to fix it in the future...but since I didn't create an issue...out of sight out of mind.

It is possible that we can simply  detect the start of a comment and enter into a sub function that handles indentation a bit different for comments.  I imagine a check that requires comment content to be indented at least as far as the opening of the block.

The next question is how should the content of the comment block be handled.

- We could ignore indentation within the content (except for the leading indentation that gets us to the comment alignment).  When indentation is spaces, you could still fail if you see leading tabs, but with tabs, I imagine you may you could fail on spaces, but I get the feeling "tab users" would mix spaces in this case.
- You could require example 1 and ignore everything after `*`. Though I am less interested in this.  I don't really want to add a comment style rule as much as I just want to make sure everything is indented proper.  If someone is doing something very contrary to existing comments, most likely I'll just tell them to change it in code review.

I think at this point, for the short term, I'll throw together a simple check to ensure indentation alignment is proper, and ignore content.  I think for spaces I may still require leading content indentation to still not be tabs, but I won't enforce the that for tabs except to ensure alignment.

**Comment by facelessuser** [comment]
Current proposal: https://github.com/facelessuser/sublime-markdown-popups/pull/38.  Implements what was discussed above.

Feel free to comment and discuss the implementation.

**Comment by deathaxe** [comment]
> You could require example 1 and ignore everything after `*`

It is an example how block comments might look like, but I agree with not enforcing leading `*`. 

> ensure indentation alignment ... ignore content

I think this is best and enough. There is no reason to enforce some kind of indention in a comment. There are no rules you could base on such checks. Best example are the lists. They need 2 spaces in order to be well aligned, while a code example may need 4. How to know? A comment is a comment and needs to be aligned to the entry correctly.

**Comment by facelessuser** [comment]
FYI: https://github.com/facelessuser/sublime-markdown-popups/commit/717c21a56029e90207584bb07342082e282cf310
